import { Image, StyleSheet, View } from 'react-native'
import { IS_EVENING } from '@/constants/theme'

// Paper, not plastic: a tiled speck of noise over the whole app at a few
// percent opacity. Lives above every screen and sheet, passes every touch
// through. The tile is generated by scripts/gen-grain.mjs — regenerate it
// there, don't edit the PNG.

const GRAIN = require('@/assets/images/grain.png')

/** Day is barely there; evening's darker ground can carry a little more. */
export const GRAIN_OPACITY = IS_EVENING ? 0.09 : 0.055

export function GrainOverlay() {
  return (
    <View pointerEvents="none" style={styles.wrap} accessibilityElementsHidden importantForAccessibility="no-hide-descendants">
      <Image source={GRAIN} style={styles.tile} resizeMode="repeat" fadeDuration={0} accessible={false} />
    </View>
  )
}

const styles = StyleSheet.create({
  wrap: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 9990,
    elevation: 9990,
  },
  tile: {
    width: '100%',
    height: '100%',
    opacity: GRAIN_OPACITY,
  },
})
