import { Image, StyleSheet, View, type StyleProp, type ViewStyle } from 'react-native'
import type { ReactNode } from 'react'
import { IS_EVENING, T } from '@/constants/theme'

// Paper, not plastic — but paper is the ground, not a film. The grain used
// to be one overlay above every screen and sheet, so cards, photos, the
// member card and the buttons all wore the same speckle and the page went
// flat (Stan, evening mode, 2026-09-06). It is now the page ground only:
// GrainGround sits as the first child of a screen's root, under everything,
// and every card, sheet and photo is a smooth surface resting on it. The
// tile is generated by scripts/gen-grain.mjs — regenerate it there, don't
// edit the PNG.

const GRAIN = require('@/assets/images/grain.png')

/** Day is quiet; evening's darker ground can carry more. */
export const GRAIN_OPACITY = IS_EVENING ? 0.14 : 0.08

/** The grain of the page. Absolute, under the content, passes every touch through. */
export function GrainGround() {
  return (
    <View
      pointerEvents="none"
      style={StyleSheet.absoluteFill}
      accessibilityElementsHidden
      importantForAccessibility="no-hide-descendants"
    >
      <Image source={GRAIN} style={styles.tile} resizeMode="repeat" fadeDuration={0} accessible={false} />
    </View>
  )
}

/** A screen's ground: the page colour with its grain, children on top. */
export function Paper({ children, style }: { children: ReactNode; style?: StyleProp<ViewStyle> }) {
  return (
    <View style={[styles.paper, style]}>
      <GrainGround />
      {children}
    </View>
  )
}

const styles = StyleSheet.create({
  paper: { flex: 1, backgroundColor: T.bg },
  tile: {
    width: '100%',
    height: '100%',
    opacity: GRAIN_OPACITY,
  },
})
