#!/usr/bin/env tsx
// scripts/sync-preset-gallery.ts
//
// Sync the web preset-sticker gallery into the app:
//   1. Read <web-repo>/public/cup-label/gallery/manifest.json
//   2. Copy each <hash>/color.png (color preview, not binarized.png which
//      is the B&W ZPL print artifact) to assets/cup-label/gallery/<hash>.png
//   3. Regenerate lib/doodle/gallery-manifest.generated.ts (require map)
//
// Default source: ~/Github/mandys_bubble_tea (override via WEB_REPO_PATH).
// Run via: npm run gallery:sync

import { promises as fs } from 'node:fs'
import { createHash } from 'node:crypto'
import path from 'node:path'
import os from 'node:os'

export type SyncManifest = { hashes: string[] }
export type SyncPlanItem = { from: string; to: string; hash: string }

const APP_ROOT = path.resolve(__dirname, '..')
const ASSETS_DIR = path.join(APP_ROOT, 'assets/cup-label/gallery')
const GENERATED_TS = path.join(APP_ROOT, 'lib/doodle/gallery-manifest.generated.ts')
const DEFAULT_WEB_REPO = path.join(os.homedir(), 'Github/mandys_bubble_tea')

export function planSync(
  manifest: SyncManifest,
  webGalleryDir: string,
  appAssetsDir: string,
): SyncPlanItem[] {
  if (!manifest || !('hashes' in manifest)) {
    throw new Error('manifest missing "hashes" field')
  }
  if (!Array.isArray(manifest.hashes)) {
    throw new Error('manifest.hashes must be an array of strings')
  }
  return manifest.hashes.map((hash) => ({
    from: path.posix.join(webGalleryDir, hash, 'color.png'),
    to: path.posix.join(appAssetsDir, `${hash}.png`),
    hash,
  }))
}

export function generateManifestModule(hashes: readonly string[]): string {
  const sorted = [...hashes].sort()
  const entries = sorted
    .map((h) => `  '${h}': require('../assets/cup-label/gallery/${h}.png'),`)
    .join('\n')
  const list = sorted.map((h) => `  '${h}',`).join('\n')

  return `// @generated by scripts/sync-preset-gallery.ts on ${new Date().toISOString()}
// DO NOT EDIT — run \`pnpm gallery:sync\` to regenerate
import type { ImageSourcePropType } from 'react-native'

export const GALLERY_MANIFEST: Record<string, ImageSourcePropType> = {
${entries}
}

export const GALLERY_HASHES: readonly string[] = [
${list}
] as const
`
}

async function sha256(file: string): Promise<string> {
  const buf = await fs.readFile(file)
  return createHash('sha256').update(buf).digest('hex')
}

async function copyIfChanged(from: string, to: string): Promise<'copied' | 'unchanged'> {
  try {
    const [fromHash, toHash] = await Promise.all([sha256(from), sha256(to)])
    if (fromHash === toHash) return 'unchanged'
  } catch {
    // dest missing → fall through to copy
  }
  await fs.copyFile(from, to)
  return 'copied'
}

async function main(): Promise<void> {
  const webRepo = process.env.WEB_REPO_PATH ?? DEFAULT_WEB_REPO
  const webGallery = path.join(webRepo, 'public/cup-label/gallery')
  const manifestPath = path.join(webGallery, 'manifest.json')

  let manifest: SyncManifest
  try {
    manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8'))
  } catch (e) {
    console.error(`[sync-preset-gallery] failed to read manifest at ${manifestPath}`)
    console.error(e)
    process.exit(1)
  }

  await fs.mkdir(ASSETS_DIR, { recursive: true })

  const plan = planSync(manifest, webGallery, ASSETS_DIR)
  let copied = 0
  let unchanged = 0
  for (const item of plan) {
    const result = await copyIfChanged(item.from, item.to)
    if (result === 'copied') copied++
    else unchanged++
  }

  await fs.writeFile(GENERATED_TS, generateManifestModule(manifest.hashes), 'utf8')

  console.log(`[sync-preset-gallery] ${manifest.hashes.length} hashes synced — ${copied} copied, ${unchanged} unchanged`)
  console.log(`[sync-preset-gallery] regenerated ${path.relative(APP_ROOT, GENERATED_TS)}`)
}

// eslint-disable-next-line @typescript-eslint/no-require-imports
if (require.main === module) {
  main().catch((e) => {
    console.error(e)
    process.exit(1)
  })
}
