// scripts/sync-preset-gallery.test.ts
//
// Pure-function tests: we don't run the script end-to-end against the
// real filesystem. Instead we exercise the planner and the codegen
// formatter directly.

import {
  planSync,
  generateManifestModule,
  type SyncManifest,
} from './sync-preset-gallery'

describe('planSync', () => {
  it('returns one copy per manifest hash', () => {
    const manifest: SyncManifest = { hashes: ['aaa', 'bbb', 'ccc'] }
    const plan = planSync(manifest, '/web/public/cup-label/gallery', '/app/assets/cup-label/gallery')
    expect(plan).toEqual([
      { from: '/web/public/cup-label/gallery/aaa/color.png', to: '/app/assets/cup-label/gallery/aaa.png', hash: 'aaa' },
      { from: '/web/public/cup-label/gallery/bbb/color.png', to: '/app/assets/cup-label/gallery/bbb.png', hash: 'bbb' },
      { from: '/web/public/cup-label/gallery/ccc/color.png', to: '/app/assets/cup-label/gallery/ccc.png', hash: 'ccc' },
    ])
  })

  it('throws on malformed manifest', () => {
    // @ts-expect-error testing bad input
    expect(() => planSync({}, '/x', '/y')).toThrow(/hashes/)
    // @ts-expect-error testing bad input
    expect(() => planSync({ hashes: 'oops' }, '/x', '/y')).toThrow(/array/)
  })
})

describe('generateManifestModule', () => {
  it('emits a 78-entry require map in deterministic key order', () => {
    const out = generateManifestModule(['zzz', 'aaa', 'mmm'])
    // Sorted alphabetically for stable diffs
    const reqLines = out.match(/require\('[^']+'\)/g) ?? []
    expect(reqLines).toEqual([
      "require('../../assets/cup-label/gallery/aaa.png')",
      "require('../../assets/cup-label/gallery/mmm.png')",
      "require('../../assets/cup-label/gallery/zzz.png')",
    ])
  })

  it('declares both GALLERY_MANIFEST and GALLERY_HASHES exports', () => {
    const out = generateManifestModule(['a', 'b'])
    expect(out).toMatch(/export const GALLERY_MANIFEST/)
    expect(out).toMatch(/export const GALLERY_HASHES/)
  })

  it('contains the @generated header', () => {
    const out = generateManifestModule(['a'])
    expect(out).toMatch(/@generated by scripts\/sync-preset-gallery\.ts/)
    expect(out).toMatch(/DO NOT EDIT/)
  })
})
